version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: docuchat-db
    environment:
      POSTGRES_DB: docuchat
      POSTGRES_USER: docuchat
      POSTGRES_PASSWORD: docuchat_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docuchat"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: docuchat-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: docuchat-backend
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-sk-test}
      DATABASE_URL: postgresql+asyncpg://docuchat:docuchat_pass@db:5432/docuchat
      REDIS_URL: redis://redis:6379/0
      FRONTEND_ORIGIN: http://localhost:3000
      JWT_SECRET: dev-secret-change-in-production
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: docuchat-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend  # For development, you can mount volumes; see README

volumes:
  postgres_data:
