{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docuchat.fullname" . }}-prometheus-config
  labels:
    {{- include "docuchat.labels" . | nindent 4 }}
data:
  prometheus.yml: |
{{ .Files.Get "../../prometheus/prometheus.yml" | indent 4 }}
  alerts.yml: |
{{ .Files.Get "../../prometheus/alerts.yml" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docuchat.fullname" . }}-prometheus
  labels:
    {{- include "docuchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "docuchat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "docuchat.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention.time={{ .Values.prometheus.retention }}'
        - '--web.enable-lifecycle'
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: storage
          mountPath: /prometheus
        resources:
          {{- toYaml .Values.resources.prometheus | nindent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "docuchat.fullname" . }}-prometheus-config
      - name: storage
        persistentVolumeClaim:
          claimName: {{ include "docuchat.fullname" . }}-prometheus-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docuchat.fullname" . }}-prometheus-storage
  labels:
    {{- include "docuchat.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docuchat.fullname" . }}-prometheus
  labels:
    {{- include "docuchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "docuchat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
